version: 2.1

jobs:
  build-and-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

  hold-for-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Hold for Destroy Approval
          command: echo "Hold for manual approval for destroy..."

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Prompt for Destroy
          command: |
            read -p "Do you want to destroy the infrastructure? (yes/no): " response
            if [ "$response" = "yes" ]; then
              terraform destroy -auto-approve
            else
              echo "Destroy canceled by user."
            fi

workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build-and-destroy:
          filters:
            branches:
              only:
                - main

      - hold-for-destroy:
          type: approval
          requires:
            - build-and-destroy

      - destroy:
          requires:
            - hold-for-destroy
          filters:
            branches:
              only:
                - main
