╷
│ Error: Module not installed
│ 
│   on main.tf line 7:
│    7: module "vpc" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 11:
│   11: module "subnets" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 16:
│   16: module "route_tables" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 21:
│   21: module "security_groups" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵
╷
│ Error: Module not installed
│ 
│   on main.tf line 26:
│   26: module "ec2_instances" {
│ 
│ This module is not yet installed. Run "terraform init" to install all modules required by this configuration.
╵

Exited with code exit status 1
error in cicrcleci  and the circleci code is   version: 2.1

jobs:
  build-and-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve

  hold-for-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Hold for Destroy Approval
          command: echo "Hold for manual approval for destroy..."

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Destroy Infrastructure
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build-and-destroy:
          filters:
            branches:
              only:
                - main

      - hold-for-destroy:
          type: approval
          requires:
            - build-and-destroy

      - destroy:
          requires:
            - hold-for-destroy
          filters:
            branches:
              only:
                - main
