version: 2.1

jobs:
  build-and-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
          
  hold-for-approval:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Pause for Manual Approval
          command: |
            echo "Waiting for manual approval..."
            # Your manual approval logic goes here, if any
            # You might integrate with external systems or use CircleCI approvals

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Terraform Init for Destroy
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build-and-destroy:
          filters:
            branches:
              only:
                - main
      - hold-for-approval:
          requires:
            - build-and-destroy
          filters:
            branches:
              only:
                - main
      - destroy:
          requires:
            - hold-for-approval
          filters:
            branches:
              only:
                - main
version: 2.1

jobs:
  build-and-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve
          
  hold-for-approval:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Pause for Manual Approval
          command: |
            echo "Waiting for manual approval..."
            # Your manual approval logic goes here, if any
            # You might integrate with external systems or use CircleCI approvals

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project
    steps:
      - checkout
      - run:
          name: Terraform Init for Destroy
          command: terraform init
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve

workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build-and-destroy:
          filters:
            branches:
              only:
                - main
      - hold-for-approval:
          requires:
            - build-and-destroy
          filters:
            branches:
              only:
                - main
      - destroy:
          requires:
            - hold-for-approval
          filters:
            branches:
              only:
                - main
