jobs:
  build:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform_project

steps:
  - checkout
  - run:
      name: Terraform Init
      command: terraform init
  - run:
      name: Terraform Plan
      command: terraform plan -out=tfplan
  - run:
      name: Terraform Apply
      command: terraform apply -auto-approve tfplan
