version: 2.1

jobs:
  build-and-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan
      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan
      - persist_to_workspace:
          root: /
          paths:
            - tfplan
            - terraform.tfstate
            - terraform.tfstate.backup

  hold-for-destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /
    steps:
      - checkout
      - attach_workspace:
          at: /
      - run:
          name: Hold for Destroy Approval
          command: echo "Hold for manual approval for destroy..."

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /
    steps:
      - checkout
      - attach_workspace:
          at: /
      - run:
          name: Terraform Destroy
          command: terraform destroy -auto-approve -state=terraform.tfstate

workflows:
  version: 2
  build-and-destroy:
    jobs:
      - build-and-destroy:
          filters:
            branches:
              only:
                - main

      - hold-for-destroy:
          type: approval
          requires:
            - build-and-destroy

      - destroy:
          requires:
            - hold-for-destroy
          filters:
            branches:
              only:
                - main
